In [136]:
%pip install torchmetrics

Defaulting to user installation because normal site-packages is not writeable
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [137]:
from amr.dataset import HybridGenomeDataset
import torch

kleb = "Klebsiella_pneumoniae_aztreonam"
kleb_genes = ["acrR","gyrA","gyrB","ompK35","ompK36","ompK37","parC","rpsL"]
staphy = "Staphylococcus_aureus_cefoxitin"
staphy_genes = ["dfrB","fusA","grlA","grlB","gyrA","ileS","pbp2","pbp4-promoter","pbp4","rpoB"]
staphy_genes = ["fusA"]
config = {
    "k" : 6,
    "pathogen" : kleb,
    "genes" : kleb_genes,
    "root_dir" : "../data/ds1",
    "batch_size" : 32,
    "learning_rate" : 0.0001,
    "epochs" : 200
}

def get_device():
    device_string = "cpu"
    if torch.mps.is_available:
        device_string = "mps"
    elif torch.cuda.is_available():
        device_string = "cuda"

    return torch.device(device_string)

In [138]:
import torch
from torch.nn.utils.rnn import pad_sequence
import torch.nn.functional as F

def hybrid_collate(batch):
    images = []
    sequences = []
    genes = []
    labels = []
    
    for (img, seq,gene), label in batch:
        images.append(img)
        sequences.append(seq)
        labels.append(label)
    
    return (torch.stack(images), pad_sequence(sequences, batch_first=True),torch.tensor(genes)), F.one_hot(torch.tensor(labels), num_classes=2)

In [139]:
from torch.utils.data import DataLoader, random_split

def get_dataloader(dataset,batch_size,shuffle=False):
    return DataLoader(dataset,batch_size=batch_size,shuffle=shuffle,collate_fn=hybrid_collate)

def get_train_val_dataloaders(dataset,batch_size=32,val_split=0.2):
    train_split_dataset, val_split_dataset = random_split(
        dataset, [1 - val_split, val_split]
    )
    train_loader = get_dataloader(train_split_dataset,batch_size,True)
    val_loader = get_dataloader(val_split_dataset,batch_size,False)
    return train_loader,val_loader

In [140]:
from torchmetrics.classification import BinaryConfusionMatrix

def step(dataloader, device, model, criterion, optimizer,val=False):    
    model.eval() if eval else model.train()

    loss, correct, total = 0, 0, 0
    confmat = BinaryConfusionMatrix().to(device)
    
    for inputs, labels in dataloader:
        images = inputs[0].to(device)
        sequences = inputs[1].to(device)
        labels = labels.to(device)
        batch_size = labels.size(0)

        outputs = model((images, sequences))
        forward_loss = criterion(outputs, labels.float())
            
        if not val:
            optimizer.zero_grad()
            forward_loss.backward()
            optimizer.step()

        loss += forward_loss.item() * batch_size
        _, predicted = torch.max(outputs, 1)
        labels = torch.argmax(labels, dim=1)  
              
        confmat.update(predicted, labels)
        total += batch_size
        correct += (predicted == labels).sum().item()

    epoch_loss = loss / total
    epoch_acc = correct / total
    matrix = confmat.compute()
    
    return epoch_loss,epoch_acc,matrix

In [141]:
from net.HybridGenomeNet import HybridGenomeNet
from torch import nn
from torch.optim.lr_scheduler import CosineAnnealingWarmRestarts

def train(model,device,criterion,optimizer):
    train_dataset = HybridGenomeDataset(
        root_dir=config["root_dir"],
        train_or_test="train",
        pathogen=config["pathogen"],
        genes=config["genes"],
        k=config["k"]
    )
    train_loader, val_loader = get_train_val_dataloaders(dataset=train_dataset,batch_size=config["batch_size"],val_split=0.2)
    scheduler = CosineAnnealingWarmRestarts(optimizer, 
                                      T_0=30,  # Initial cycle length
                                      T_mult=1,  # Cycle length multiplier
                                      eta_min=1e-8)  # Minimum LR
    
    num_epochs = config["epochs"]
    for epoch in range(num_epochs):
        epoch_train_loss, epoch_train_acc,train_matrix = step(
            train_loader, device, model, criterion, optimizer
        )
        with torch.no_grad():
            epoch_val_loss, epoch_val_acc,val_matrix = step(
                val_loader, device, model, criterion,optimizer,True
            )
            print(val_matrix)
        scheduler.step(epoch_val_loss)

        print(
            f"Epoch {epoch+1}/{num_epochs} | "
            f"Train Loss: {epoch_train_loss:.4f} | "
            f"Train Acc: {epoch_train_acc:.4f} | "
            f"Val Loss: {epoch_val_loss:.4f} | "
            f"Val Acc: {epoch_val_acc:.4f}"
        )

    torch.save(model.state_dict(), "model_weights.pth")
    
    return model


In [142]:
def test(model,device,criterion,optimizer):
    
    for i in range(0,len(config["genes"])):
        gene = config["genes"][i]
        print("Gene: ",gene)
    
        test_dataset = HybridGenomeDataset(
            root_dir=config["root_dir"],
            train_or_test="test",
            pathogen=config["pathogen"],
            genes=[gene],
            k=config["k"]
        )
        test_loader = get_dataloader(test_dataset,config["batch_size"],False)
        with torch.no_grad():
            test_loss, test_acc,confusion_matrix = step(test_loader, device, model, criterion,optimizer,True)
            print(
                f"Test Results| " f"Test Loss: {test_loss:.4f} | " f"Test Acc: {test_acc:.4f}"
            )
            print(confusion_matrix)

In [143]:

device = get_device()
model = HybridGenomeNet().to(device)
class_weights = torch.tensor([4.0,1.0]).to(device=device)
criterion = nn.CrossEntropyLoss(weight=class_weights)
optimizer = torch.optim.Adam(model.parameters(), lr=config["learning_rate"])

model = train(model,device,criterion,optimizer)
test(model,device,criterion,optimizer)

tensor([[  0,  18],
        [  0, 198]], device='mps:0')
Epoch 1/200 | Train Loss: 0.7709 | Train Acc: 0.8866 | Val Loss: 0.7248 | Val Acc: 0.9167
tensor([[  0,  18],
        [  0, 198]], device='mps:0')
Epoch 2/200 | Train Loss: 0.7208 | Train Acc: 0.9190 | Val Loss: 0.7272 | Val Acc: 0.9167
tensor([[  0,  18],
        [  0, 198]], device='mps:0')
Epoch 3/200 | Train Loss: 0.7169 | Train Acc: 0.9190 | Val Loss: 0.7318 | Val Acc: 0.9167
tensor([[  0,  18],
        [  0, 198]], device='mps:0')
Epoch 4/200 | Train Loss: 0.7136 | Train Acc: 0.9190 | Val Loss: 0.7475 | Val Acc: 0.9167
tensor([[  0,  18],
        [  0, 198]], device='mps:0')
Epoch 5/200 | Train Loss: 0.7162 | Train Acc: 0.9190 | Val Loss: 0.7382 | Val Acc: 0.9167
tensor([[  0,  18],
        [  0, 198]], device='mps:0')
Epoch 6/200 | Train Loss: 0.7114 | Train Acc: 0.9190 | Val Loss: 0.7495 | Val Acc: 0.9167
tensor([[  0,  18],
        [  0, 198]], device='mps:0')
Epoch 7/200 | Train Loss: 0.7023 | Train Acc: 0.9190 | Val Lo

In [144]:
device = get_device()
model = HybridGenomeNet().to(device)
model.load_state_dict(torch.load("model_weights.pth"))

test(model,device,criterion,optimizer)

Gene:  acrR
Test Results| Test Loss: 2.3023 | Test Acc: 0.7333
tensor([[ 0,  4],
        [ 0, 11]], device='mps:0')
Gene:  gyrA
Test Results| Test Loss: 3.0777 | Test Acc: 0.7333
tensor([[ 0,  4],
        [ 0, 11]], device='mps:0')
Gene:  gyrB
Test Results| Test Loss: 3.4077 | Test Acc: 0.7333
tensor([[ 0,  4],
        [ 0, 11]], device='mps:0')
Gene:  ompK35
Test Results| Test Loss: 2.9119 | Test Acc: 0.7333
tensor([[ 0,  4],
        [ 0, 11]], device='mps:0')
Gene:  ompK36
Test Results| Test Loss: 4.0282 | Test Acc: 0.7333
tensor([[ 0,  4],
        [ 0, 11]], device='mps:0')
Gene:  ompK37
Test Results| Test Loss: 3.9251 | Test Acc: 0.7333
tensor([[ 0,  4],
        [ 0, 11]], device='mps:0')
Gene:  parC
Test Results| Test Loss: 2.9350 | Test Acc: 0.6000
tensor([[0, 4],
        [2, 9]], device='mps:0')
Gene:  rpsL
Test Results| Test Loss: 1.8921 | Test Acc: 0.7333
tensor([[ 0,  4],
        [ 0, 11]], device='mps:0')
